/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: caa4a24ca6955c3810a8249a6e612ee8)
interface __BaseEnv_Env {
	ARTWORK: R2Bucket;
	DB: D1Database;
	AUTH_PROVIDER: string;
	AUTH_ENABLED: string;
	SIGNUP_ENABLED: string;
	APP_ORIGIN: string;
	OIDC_ISSUER: string;
	OIDC_CLIENT_ID: string;
	AUTH0_CONNECTION: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUTH_PROVIDER" | "AUTH_ENABLED" | "SIGNUP_ENABLED" | "APP_ORIGIN" | "OIDC_ISSUER" | "OIDC_CLIENT_ID" | "AUTH0_CONNECTION">> {}
}
